[package]
name = "clean-empty-lines"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "clean-empty-lines" # Der Name des ausführbaren Programms
path = "src/main.rs"      # Der Pfad zur Hauptdatei des Binär-Targets

[dependencies]
# Hier würden zusätzliche Abhängigkeiten stehen
